### PR TITLE
Introduce state persistency

### PR DESCRIPTION
**Pull request by sventschui**
How to handle input fields? Go for bound values? Setting all input into stores?

### CODE REVIEW

**Comment by davidknezic** [comment]
Cool thing if you save input into stores: you could do co-browsing and you can save input if you accidentally leave the page.

**Comment by sventschui** [comment]
Yes. But should we implement some sort of synchronisation or should be go for bound input values? What drawbacks do bound values have?

**Comment by davidknezic** [comment]
Well I guess, it would reduce boilderplate code. Maybe with the [ReactLink mixin](https://facebook.github.io/react/docs/two-way-binding-helpers.html)?

I don't currently see any drawbacks..

**Comment by sventschui** [comment]
Problem is we would have to go back to React.createClass instead of ES6 classes to use mixins

**Comment by sventschui** [comment]
I simply save the latest query in the store and populate the input field on start up (defaultValue)

**Pull request merged**
